name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Change this if you use a different default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.7'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Streamlit app
      run: |
        nohup streamlit run app.py &
        echo "Streamlit app is running"
